[versions]
dokka = "2.0.0"
dokkatoo = "2.4.0"
jvmToolchain = "21"

kotlin = "2.1.21"
mikrom = "0.1.0-SNAPSHOT"

kotest = "5.9.1"
kotest-propertyArbsExtension = "2.1.2"

gradlePlugin-ktlint = "12.1.2"
gradlePlugin-testlogger = "4.0.0"

kotlinBinaryCompatibilityValidator = "0.17.0"
kotlinx-coroutines = "1.10.2"
nmcp = "1.2.0"

[libraries]

## Mikrom
mikrom-core = { module = "io.github.kantis:mikrom-core", version.ref = "mikrom" }
mikrom-jdbc = { module = "io.github.kantis:mikrom-jdbc", version.ref = "mikrom" }
mikrom-r2dbc = { module = "io.github.kantis:mikrom-r2dbc", version.ref = "mikrom" }

h2 = { module = "com.h2database:h2", version = "2.3.232" }
postgresql = { module = "org.postgresql:postgresql", version = "42.6.0" }
r2dbc-postgresql = { module = "org.postgresql:r2dbc-postgresql", version = "1.0.7.RELEASE" }
r2dbc-spi = { module = "io.r2dbc:r2dbc-spi", version = "1.0.0.RELEASE" }
r2dbc-pool = { module = "io.r2dbc:r2dbc-pool", version = "1.0.2.RELEASE" }
slf4j-api = { module = "org.slf4j:slf4j-api", version = "2.0.9" }
logback-classic = { module = "ch.qos.logback:logback-classic", version = "1.4.11" }

kotlinxCoroutinesReactor = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactor", version.ref = "kotlinx-coroutines" }
kotlinxCoroutinesReactive = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-reactive", version.ref = "kotlinx-coroutines" }
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }

## Kotest ##
kotest-assertionsCore = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertionsJson = { module = "io.kotest:kotest-assertions-json", version.ref = "kotest" }
kotest-datatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotest" }
kotest-frameworkApi = { module = "io.kotest:kotest-framework-api", version.ref = "kotest" }
kotest-frameworkEngine = { module = "io.kotest:kotest-framework-engine", version.ref = "kotest" } # Not included in the BOM
kotest-frameworkDatatest = { module = "io.kotest:kotest-framework-datatest", version.ref = "kotest" }
kotest-runnerJunit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }

kotest-propertyArbsExtension = { module = "io.kotest.extensions:kotest-property-arbs", version.ref = "kotest-propertyArbsExtension" }
kotestExtensions-testcontainers = { module = "io.kotest.extensions:kotest-extensions-testcontainers", version = "2.0.2" }

testcontainers-postgresql = { module = "org.testcontainers:postgresql", version = "1.20.0" }
hikari = { module = "com.zaxxer:HikariCP", version = "6.3.0" }

kotestPlugin-embeddedCompiler = { module = "io.kotest:kotest-framework-multiplatform-plugin-embeddable-compiler" }
kotestPlugin-multiplatform = { module = "io.kotest:kotest-framework-multiplatform-plugin-gradle" }

jetbrains-annotations = { module = "org.jetbrains:annotations", version = "26.0.2" }

## Dokka plugins ##
dokka-allModulesPage = { module = "org.jetbrains.dokka:all-modules-page-plugin", version.ref = "dokka" }
dokka-templating = { module = "org.jetbrains.dokka:templating-plugin", version.ref = "dokka" }

### Gradle plugins ###
# Maven coordinates of Gradle plugins. Used in ./build-logic/build.gradle.kts.
gradlePlugin-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
gradlePlugin-testlogger = { module = "com.adarshr:gradle-test-logger-plugin", version.ref = "gradlePlugin-testlogger" }
gradlePlugin-kotest = { module = "io.kotest:kotest-framework-multiplatform-plugin-gradle", version.ref = "kotest" }

gradlePlugin-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
gradlePlugin-dokkatoo = { module = "dev.adamko.dokkatoo:dokkatoo-plugin", version.ref = "dokkatoo" }

gradlePlugin-ktlint = { module = "org.jlleitschuh.gradle:ktlint-gradle", version.ref = "gradlePlugin-ktlint" }
gradlePlugin-kotlinBinaryCompatibilityValidator = { module = "org.jetbrains.kotlinx:binary-compatibility-validator", version.ref = "kotlinBinaryCompatibilityValidator" }
gradlePlugin-nmcp = { module = "com.gradleup.nmcp:com.gradleup.nmcp.gradle.plugin", version.ref = "nmcp" }

[bundles]


[plugins]
# If plugin will be used by conventions, define plugins in ./build-logic/build.gradle.kts to avoid error:
# The Kotlin Gradle plugin was loaded multiple times in different subprojects, which is not supported and may break the build.

nmcpAggregation = { id = "com.gradleup.nmcp.aggregation", version.ref = "nmcp" }
